### ISSUE TITLE
Can't rando a rando *Solved*

### ISSUE THREAD

**Issue by SenseiLeRoof** [MottZilla/SOTN_AR#1]
Any attempt to play a game run through both sotn.io and this results in the game crashing during post-prologue loading. Direct edit vs. ppf in either case doesn't matter.

**Comment by MottZilla** [comment]
Please be more specific. What exactly did you do? For example what options did you set in SOTN_AR and what options did you use on sotn.io? I will need more details to help.

**Comment by SenseiLeRoof** [comment]
sotn.io options used each time:
Complexity 9
Checked: Enemy drops, item locations, item stats, starting equipment, prologue rewards, music, relic locations (equipment)
Tournament mode (sometimes)

AR options:
Free shop relic, fast wolf, clock statue always open, area rando, starting: Leap Stone
Creature ??? (sometimes)
Include EDC/ECC (sometimes, only with Create PPF method)

Methods attempted:
Direct edit through both randomizers
PPF from .io then direct edit from AR
Direct edit from .io then PPF from AR
PPF from both, patch both afterward
PPF from .io, patch, copy original for .org file, PPF from AR, patch
PPF from .io, patch, copy patched for .org file, PPF from AR, patch

In all cases, using web version of .io and latest release of AR

**Comment by MottZilla** [comment]
There is a problem, thanks for bringing it to my attention. For now you can use the older releases. Version 2023-06-30 should work, if not the one prior to it 2023-06-07 will. It will get fixed in the next update. 

The error was found and fixed. Thanks again. Keep an eye out for a new version soon.

**Comment by MottZilla** [comment]
New version posted that fixes the issue. It was a typo in the PSX code causing an exception. Please let me know that the new version works for you or if it doesn't. If it's working for you I'll close this issue.

**Comment by SenseiLeRoof** [comment]
Looks like it's fixed.

**Comment by MottZilla** [comment]
Thanks!
